#!/usr/bin/env bash
# bootstrap script
# run this to generate the configure script and other files needed
# by the build system (e.g. source files to compile).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pushd "$SCRIPT_DIR" >/dev/null
trap 'popd >/dev/null' EXIT

# sanity check that the script lives at the project root
if [ ! -f "configure.ac" ]; then
    echo "Error: configure.ac not found next to autogen.sh."
    exit 1
fi

########################################

echo "Generating source file list..."
SOURCES_FILE="src/Makefile.sources"
mkdir -p "$(dirname "$SOURCES_FILE")"

# find source files, formatted as Makefile continuation lines
find_sources() {
    find "$@" -not -path '*/[@.]*' -type f '(' -name "*.cpp" -o -name "*.c" ')' | LC_ALL=C sort | \
        sed 's/$/ \\/' | \
        sed 's/^/\t/'
}

# write a conditional source block
# usage: cond_sources "if CONDITION" "VARIABLE" [find args...]
cond_sources() {
    printf '\n%s\n%s := \\\n' "$1" "$2" >> "$SOURCES_FILE"
    shift 2
    find_sources "$@" >> "$SOURCES_FILE"
    # shellcheck disable=SC2016
    printf '\t$(NULL)\nendif\n' >> "$SOURCES_FILE"
}

# conditional sources (renderer, audio, platform)
cat > "$SOURCES_FILE" << 'EOF'
# Automatically generated by autogen.sh - DO NOT EDIT
EOF

cond_sources "if USE_GL"       "GL_SHARED_SOURCES" src/Engine/Renderer/OpenGL -maxdepth 1
cond_sources "if USE_OPENGL"   "GL_CORE_SOURCES"   src/Engine/Renderer/OpenGL/Core
cond_sources "if USE_OPENGLES" "GLES_SOURCES"      src/Engine/Renderer/OpenGL/ES
cond_sources "if USE_DX11"     "DX11_SOURCES"      src/Engine/Renderer/DirectX11
cond_sources "if USE_SDLGPU"   "SDLGPU_SOURCES"    src/Engine/Renderer/SDLGPU
cond_sources "if USE_SOLOUD"   "SOLOUD_SOURCES"    src/Engine/Sound/SoLoud
cond_sources "if USE_BASS"     "BASS_SOURCES"      src/Engine/Sound/BASS
cond_sources "if USE_FFMPEG"   "FFMPEG_SOURCES"    src/Engine/Resources/FFmpegInterop # i don't know what folder this should really go in, whatever
cond_sources "if WIN_PLATFORM" "WIN_SOURCES"       src/Platform/Windows
cond_sources "if BUILD_TESTS"  "TEST_SOURCES"      src/App/Tests

# glad (needed for native GL/GLES builds; WASM has its own loader)
# shellcheck disable=SC2016
{
    printf '\nif !WASM_PLATFORM\n'
    printf 'if USE_OPENGL\nGLAD_SOURCES := \\\n'
    find_sources libraries/glad -maxdepth 1 -name 'glad_*gl*'
    printf '\t$(NULL)\nendif\n'
    printf 'if USE_OPENGLES\nGLAD_SOURCES := \\\n'
    find_sources libraries/glad -maxdepth 1 -name 'glad_*gl*'
    printf '\t$(NULL)\nendif\n'
    printf 'endif\n'
} >> "$SOURCES_FILE"

# unconditional sources + conditional variable references
{
    printf '\nmikosu_SOURCES = \\\n'

    find_sources src libraries \
        -not -path 'src/Engine/Renderer/DirectX11/*' \
        -not -path 'src/Engine/Renderer/SDLGPU/*' \
        -not -path 'src/Engine/Renderer/OpenGL/*' \
        -not -path 'src/Engine/Sound/BASS/*' \
        -not -path 'src/Engine/Sound/SoLoud/*' \
        -not -path 'src/Platform/Windows/*' \
        -not -path 'src/Engine/Resources/FFmpegInterop/*' \
        -not -path 'libraries/glad/*' \
        -not -path 'src/App/Tests/*'

    cat << 'EOF'
	$(GL_SHARED_SOURCES) \
	$(GL_CORE_SOURCES) \
	$(GLES_SOURCES) \
	$(DX11_SOURCES) \
	$(SDLGPU_SOURCES) \
	$(GLAD_SOURCES) \
	$(SOLOUD_SOURCES) \
	$(BASS_SOURCES) \
	$(WIN_SOURCES) \
	$(FFMPEG_SOURCES) \
	$(TEST_SOURCES) \
	$(NULL)
EOF
} >> "$SOURCES_FILE"

mkdir -p build-aux

########################################

check_tool() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Error: $1 not found. Please install $2."
        exit 1
    fi
}

check_tool "aclocal" "automake"
check_tool "automake" "automake"
check_tool "autoconf" "autoconf"
check_tool "pkgconf" "pkgconf"

echo "Running autotools..."
autoreconf -iv

echo "
Bootstrap complete. You can now build mikosu either:

For development (recommended, out-of-tree build):
  mkdir build
  cd build
  ../configure [options]
  make
  make install

For end-users (in-tree build):
  ./configure [options]
  make
  make install

Some configure options:
  --prefix=/usr           Install to /usr instead of ./dist
  --enable-debug          Enable debug build
  --enable-native         Enable native CPU optimizations (-march=native -mtune=native)
  --enable-system-deps    Prefer sharing system dependencies instead of building them from source
  --disable-static        Try to build/link libraries dynamically instead of statically
  --enable-lto            Enable link-time optimization (default: used if available)

For a full list of options, run: ./configure --help
"
