#!/usr/bin/env python3
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

keywords = ["_", "tformat"]

# Add a new language here to automatically generate a new .po file!
# Sorting by player count here... but this will get messy if we have many languages
languages = {
    "ru": "Русский",
    "ja": "日本語",
    "fr": "Français",
    "pl": "Polski",
    "de": "Deutsch",
}

# Resolve both inputs to absolute paths for unambiguous filesystem ops. xgettext records
# the path string it was given verbatim into .pot/.po `#:` references, so to keep those
# references identical across machines we feed it srcdir-relative paths ("src/App/...")
# and run with cwd=srcdir_abs. This is independent of how the script was invoked
# (make uses ".." / ".", a manual run might use absolute paths) and where builddir lives
# (in-tree under srcdir, sibling, /tmp/..., or anywhere else).
srcdir_abs = Path(sys.argv[1]).resolve()
builddir_abs = Path(sys.argv[2]).resolve()

# builddir is preserved as-passed (typically ".") for manifest entries, so they match
# make's $(builddir) form and the gen/%.mo pattern rule.
builddir = Path(sys.argv[2])

gen_dir = builddir_abs / "gen"
gen_dir.mkdir(parents=True, exist_ok=True)

pot_path = srcdir_abs / "translations" / "neomod.pot"
translations_h_path = gen_dir / "translations.h"
manifest_path = gen_dir / "locale_embed.manifest"

# Translation calls only live in .cpp - .h files contain raw-string OBJ blobs
# and other non-C content that confuses xgettext.
# TODO: just use TRANSLATION_SRCS from Makefile?
SOURCES = sorted(
    str(p.relative_to(srcdir_abs)) for p in (srcdir_abs / "src").rglob("*.cpp")
)


def parse_pot_msgids(pot_text: str) -> list[str]:
    """Extract msgid payloads from a .pot, returning each as a decoded Python string
    (escape sequences resolved to their actual characters). Sorting these decoded
    strings matches std::string_view::operator< byte order on the C++ side, which
    string_index()'s binary search and the static_assert in i18n.h depend on."""
    msgids: list[str] = []
    current: str | None = None

    def flush() -> None:
        nonlocal current
        if current:
            msgids.append(_decode_po_escapes(current))
        current = None

    for raw in pot_text.splitlines():
        s = raw.rstrip()
        if s.startswith("msgid "):
            flush()
            current = _strip_quotes(s[len("msgid "):])
        elif s.startswith("msgid_plural "):
            # plural variant lives at the same index as the singular we just captured
            flush()
        elif s.startswith("msgstr"):
            flush()
        elif s == "" or s.startswith("#"):
            flush()
        elif current is not None and s.startswith('"') and s.endswith('"'):
            current += _strip_quotes(s)
    flush()
    return msgids


def _strip_quotes(s: str) -> str:
    s = s.strip()
    if len(s) >= 2 and s.startswith('"') and s.endswith('"'):
        return s[1:-1]
    return ""


# .po and C++ share a near-identical string literal grammar; xgettext currently emits only
# \", \\, \n, \t, \r from the printable-character subset, but octal/hex escapes are legal
# too. We decode the full set so the round-trip survives any future xgettext output.
_PO_ESCAPES = {"n": "\n", "t": "\t", "r": "\r", "b": "\b", "f": "\f", "a": "\a",
               "v": "\v", "\\": "\\", '"': '"', "?": "?", "'": "'"}
_C_ESCAPES = {"\\": "\\\\", '"': '\\"', "\n": "\\n", "\t": "\\t", "\r": "\\r"}


def _decode_po_escapes(s: str) -> str:
    out: list[str] = []
    i = 0
    while i < len(s):
        if s[i] == "\\" and i + 1 < len(s) and s[i + 1] in _PO_ESCAPES:
            out.append(_PO_ESCAPES[s[i + 1]])
            i += 2
        else:
            out.append(s[i])
            i += 1
    return "".join(out)


def _encode_c_escapes(s: str) -> str:
    return "".join(_C_ESCAPES.get(c, c) for c in s)


def build_translations_h(msgids: list[str]) -> str:
    # plain C arrays instead of std::to_array: avoids a fat per-TU template instantiation
    # in every TU that includes i18n.h
    out = """// Auto-generated by gen_translations.py - do not edit
#pragma once
#include <string_view>

namespace i18n {

using std::string_view_literals::operator""sv;

inline constexpr std::string_view TRANSLATABLE_STRINGS[] = {
"""
    for s in sorted(set(msgids)):
        out += f'    "{_encode_c_escapes(s)}"sv,\n'
    out += """};

struct Language final {
    std::string_view code;
    std::string_view name;
};

inline constexpr Language LANGUAGES[] = {
    Language{"en"sv, "English"sv},
"""
    for code, lang in languages.items():
        out += f'    Language{{"{code}"sv, "{lang}"sv}},\n'
    out += "};\n}  // namespace i18n\n\n"
    return out


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def write_bytes_if_changed(path: Path, content: bytes) -> bool:
    if path.exists() and path.read_bytes() == content:
        return False
    path.write_bytes(content)
    return True


def xgettext_supports_flag_value(flag_value: str) -> bool:
    """Probe whether xgettext accepts `--flag=keyword:1:<flag_value>`. Older xgettext
    (pre-gettext-0.22, e.g. Ubuntu 22.04's 0.21) rejects values it doesn't recognize
    with: 'A --flag argument doesn't have the <keyword>:<argnum>:[pass-]<flag> syntax'.
    Used to keep the script working on CI runners shipping older gettext while still
    enabling c++-format validation locally where available."""
    with tempfile.NamedTemporaryFile("w", suffix=".cpp", dir=str(gen_dir), delete=False) as tmp:
        probe = Path(tmp.name)
    try:
        result = subprocess.run(
            ["xgettext", f"--flag=_:1:{flag_value}", "-o", "-", str(probe)],
            capture_output=True,
        )
        return result.returncode == 0
    finally:
        probe.unlink(missing_ok=True)


def build_mo(po_path: Path, mo_path: Path) -> None:
    """Compile .po -> .mo via msgfmt with cmp-and-write. We own .mo generation here
    (instead of a separate Makefile rule) so the entire translation pipeline lives in
    one recipe - the stamp file - which avoids a make-graph race: with the old per-.mo
    rule, msgmerge's mid-recipe rewrite of .po landed AFTER make had already decided
    .mo was up to date, leaving a stale binary_embed.cpp until the *next* make invocation.
    Compiling here means the .mo's actual disk mtime is set before make's downstream
    dep checks run."""
    with tempfile.NamedTemporaryFile("wb", suffix=".mo", dir=str(gen_dir), delete=False) as tmp:
        tmp_mo = Path(tmp.name)
    try:
        # --check-format makes the build fail on format-specifier mismatches in translations
        # instead of silently producing a .mo that fmt::vformat will std::abort on at runtime
        # (we build with -fno-exceptions, so fmt's default error path is abort).
        subprocess.run(
            ["msgfmt", "--check-format", "-o", str(tmp_mo), str(po_path)],
            check=True,
        )
        new_bytes = tmp_mo.read_bytes()
        if not mo_path.exists() or mo_path.read_bytes() != new_bytes:
            shutil.move(str(tmp_mo), str(mo_path))
            tmp_mo = None
    finally:
        if tmp_mo is not None and tmp_mo.exists():
            tmp_mo.unlink()


# Regenerate .pot into a temp file so we can decide whether to actually update it.
with tempfile.NamedTemporaryFile("w", suffix=".pot", dir=str(gen_dir), delete=False) as tmp:
    temp_pot = Path(tmp.name)

try:
    xgettext_args = (
        ["xgettext"]
        + ["--keyword=" + k for k in keywords]
        + [
            "--omit-header",
            # --no-wrap matches the msgmerge flag below; otherwise xgettext wraps msgid lines
            # at 78 cols and msgmerge re-wraps differently per platform.
            "--no-wrap",
            # Keep the source-file reference for translator tooling, but drop line numbers so
            # `#:` comments don't churn whenever unrelated code edits shift line offsets.
            "--add-location=file",
            # Pick up "// xgettext: no-c-format" markers on problem strings (e.g. "100% to 150%"
            # that would otherwise get spurious c-format flags).
            "--add-comments=TRANSLATORS",
            "--sort-by-file",
            "-o", str(temp_pot),
            "--package-name=neomod",
        ]
    )

    # tformat's first argument is a fmt::format_string, so let msgfmt --check-format validate
    # translator format mismatches. We deliberately do NOT pass --flag=_:1:no-c-format - that
    # would globally disable c-format detection for every _() string, which is too broad: it
    # would silently hide format-string bugs if anyone ever feeds an _() string to printf or
    # similar. The literal-`%` strings (ModSelector.cpp "100%" etc.) use per-call-site
    # `// xgettext: no-c-format` comments to suppress the flag locally instead.
    #
    # 'c++-format' is gettext 0.22+ (2023). Older xgettext (e.g. Ubuntu 22.04 ships 0.21)
    # rejects the flag value and aborts, so probe support and degrade gracefully on CI.
    # Without the flag, msgfmt --check-format still validates _()-marked strings tagged
    # 'c-format' by xgettext's auto-detection - just not tformat-specific fmt syntax.
    if xgettext_supports_flag_value("c++-format"):
        xgettext_args.append("--flag=tformat:1:c++-format")
    else:
        print("xgettext < 0.22 detected; skipping --flag=tformat:1:c++-format "
              "(translator format-string validation for tformat() disabled).",
              file=sys.stderr)

    subprocess.run(xgettext_args + SOURCES, cwd=str(srcdir_abs), check=True)

    msgids = parse_pot_msgids(temp_pot.read_text(encoding="utf-8"))
    new_translations_h = build_translations_h(msgids)

    # If translations.h content is unchanged, the set of translatable strings is the same.
    # Skip rewriting .pot/.po too, to avoid line-number churn on unrelated source edits.
    if (
        translations_h_path.exists()
        and translations_h_path.read_text(encoding="utf-8") == new_translations_h
    ):
        # Manifest and .mo files may be missing on first-build-after-clean even though
        # the string set didn't change - generate them if needed (cmp-and-write keeps
        # the existing ones' mtimes intact for the no-op case).
        manifest_content = "\n".join(f"locale_{code} : {builddir}/gen/{code}.mo" for code in languages) + "\n"
        write_if_changed(manifest_path, manifest_content)
        for code in languages:
            po = srcdir_abs / "translations" / f"{code}.po"
            mo = gen_dir / f"{code}.mo"
            if po.exists():
                build_mo(po, mo)
        sys.exit(0)

    # mikosu: a fresh build dir has no translations.h yet, which counted as "strings changed" and rewrote
    # the tracked .pot/.po with this machine's gettext (gettext < 0.22 formats them differently, leaving a
    # dirty tree after every clean build). Only rewrite the tracked files when the set of strings really
    # differs from the committed .pot; otherwise build from the committed .po as they are.
    if pot_path.exists() and sorted(parse_pot_msgids(pot_path.read_text(encoding="utf-8"))) == sorted(msgids):
        translations_h_path.write_text(new_translations_h, encoding="utf-8")
        manifest_content = "\n".join(f"locale_{code} : {builddir}/gen/{code}.mo" for code in languages) + "\n"
        write_if_changed(manifest_path, manifest_content)
        for code in languages:
            po = srcdir_abs / "translations" / f"{code}.po"
            mo = gen_dir / f"{code}.mo"
            if po.exists():
                build_mo(po, mo)
        sys.exit(0)

    print("Strings changed, updating translations.")

    shutil.move(str(temp_pot), str(pot_path))
    temp_pot = None  # don't unlink in finally
finally:
    if temp_pot is not None and temp_pot.exists():
        temp_pot.unlink()

translations_h_path.write_text(new_translations_h, encoding="utf-8")

# Generate or update language .po files to match latest strings. msgmerge writes to a
# temp file (not in-place) so we can pipe through msgattrib and cmp-and-write the final
# result - unchanged .po keeps its mtime, which keeps downstream .mo / binary_embed off
# the rebuild list when only line-number references shifted.
for code, lang in languages.items():
    po = srcdir_abs / "translations" / f"{code}.po"
    if po.exists():
        with tempfile.NamedTemporaryFile("wb", suffix=".po", dir=str(gen_dir), delete=False) as tmp:
            tmp_po = Path(tmp.name)
        try:
            # --no-wrap keeps msgstr lines unbroken, so .po output is identical regardless of
            # the locale/libc/msgmerge version that produced it (default-wrapped output churns
            # across platforms). --add-location=file matches the xgettext flag above so the
            # `#:` references in .po stay aligned with .pot if msgmerge ever runs standalone.
            subprocess.run(
                ["msgmerge", "--no-wrap", "--add-location=file",
                 "-o", str(tmp_po), str(po), str(pot_path)],
                check=True,
            )
            # msgmerge keeps removed-but-previously-translated entries around as `#~ msgid ...`
            # blocks (standard gettext convention so translators can recover history). For a
            # codebase that churns translatable strings, the obsolete block grows without bound
            # and noises up .po diffs. If a translator ever needs the prior text, it's still in git history.
            result = subprocess.run(
                ["msgattrib", "--no-obsolete", "--no-wrap", "--add-location=file",
                 str(tmp_po)],
                check=True, stdout=subprocess.PIPE,
            )
            write_bytes_if_changed(po, result.stdout)
        finally:
            if tmp_po.exists():
                tmp_po.unlink()
    else:
        print(f"{code}.po doesn't exist, generating a new file.")
        subprocess.run(
            [
                "msginit",
                "--no-translator",
                "-i", str(pot_path),
                "-o", str(po),
                "-l", code,
            ],
            check=True,
        )

# Compile each .po into a .mo. See build_mo's docstring for why this lives here instead
# of in Makefile.am: it eliminates the make-graph race that left binary_embed stale for
# one make invocation after any translatable-string change.
for code in languages:
    po = srcdir_abs / "translations" / f"{code}.po"
    mo = gen_dir / f"{code}.mo"
    if po.exists():
        build_mo(po, mo)

# locale_embed.manifest is consumed within the same build, so entries are written
# using $(builddir)-relative paths to match gen_binary_embed.py's -F flag (which does not
# prepend --base-dir) and the gen/%.mo pattern rule in Makefile.am.
manifest_content = "\n".join(f"locale_{code} : {builddir}/gen/{code}.mo" for code in languages) + "\n"
write_if_changed(manifest_path, manifest_content)
